services:
  backend:
    #HONO BACKEND
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nutripioneer-backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
  frontend:
    build:
      context: ./nutripioneer
      dockerfile: Dockerfile
    container_name: nutripioneer-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:3001
      - NEXT_PUBLIC_API_URL=http://5.78.150.159
    depends_on:
      - backend
